# TCL File Generated by Component Editor 13.0
# Fri May 27 14:23:50 GFT 2016
# DO NOT MODIFY


# 
# piosampler "piosampler" v1.0
# Ricardo_Cayssials 2016.05.27.14:23:50
# piosampler Qsys Component
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0
#package require -exact sopc 10.0


# 
# module piosampler
# 
set_module_property DESCRIPTION "piosampler Qsys Component for SOPC monitoring"
set_module_property NAME piosampler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP gRTOS
set_module_property AUTHOR Ricardo_Cayssials
set_module_property DISPLAY_NAME "piosampler Qsys Component for SOPC monitoring"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ELABORATION_CALLBACK elaborate
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false

#set_module_property SIMULATION_MODEL_IN_VHDL true
#set_module_property DATASHEET_URL http://www.altera.com/literature/hb/qts/qsys_interconnect.pdf


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL piosampler
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file piosampler.vhd VHDL PATH piosampler.vhd


add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL piosampler
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file piosampler.vhd VHDL PATH piosampler.vhd

# 
# parameters
# 
#**************************************************************************
#**************************************************************************
# piosampler PARAMETERS
#**************************************************************************
#**************************************************************************

add_parameter RX_DATA_FIFO_DEPTH INTEGER 5 RX_DATA_FIFO_DEPTH
set_parameter_property RX_DATA_FIFO_DEPTH DEFAULT_VALUE 1024
set_parameter_property RX_DATA_FIFO_DEPTH DISPLAY_NAME {Depth of the RX DATA FIFO}
set_parameter_property RX_DATA_FIFO_DEPTH TYPE INTEGER
set_parameter_property RX_DATA_FIFO_DEPTH UNITS None
set_parameter_property RX_DATA_FIFO_DEPTH DISPLAY_UNITS "Words"
set_parameter_property RX_DATA_FIFO_DEPTH ALLOWED_RANGES {128 256 512 1024 2048 4096}
set_parameter_property RX_DATA_FIFO_DEPTH DESCRIPTION {Depth of the RX DATA FIFO}
set_parameter_property RX_DATA_FIFO_DEPTH HDL_PARAMETER true

add_parameter DEVICE_FAMILY STRING 
set_parameter_property DEVICE_FAMILY SYSTEM_INFO {DEVICE_FAMILY}
set_parameter_property DEVICE_FAMILY DESCRIPTION DEVICE_FAMILY
set_parameter_property DEVICE_FAMILY HDL_PARAMETER true
add_display_item "" DEVICE_FAMILY PARAMETER
 
add_parameter RX_DATA_FIFO_WIDTHU INTEGER 
set_parameter_property RX_DATA_FIFO_WIDTHU  DERIVED true
set_parameter_property RX_DATA_FIFO_WIDTHU TYPE INTEGER
set_parameter_property RX_DATA_FIFO_WIDTHU UNITS None
set_parameter_property RX_DATA_FIFO_WIDTHU HDL_PARAMETER true
add_display_item "" RX_DATA_FIFO_WIDTHU PARAMETER



# 
# display items
# 
add_display_item "" "System Properties" GROUP ""
add_display_item "" Interrupt GROUP ""




# 
# connection point clock_reset
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock AVALON_CLK clk Input 1


# 
# connection point clock_reset_reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset RESET reset Input 1



#**************************************************************************
#**************************************************************************
# AVALON INTERFACES
#**************************************************************************


#**************************************************************************
#**************************************************************************
# piosampler INTERFACES
#**************************************************************************
#**************************************************************************

# 
# connection point sampler
# 
add_interface sampler conduit end
set_interface_property sampler associatedClock clock
set_interface_property sampler associatedReset reset
set_interface_property sampler ENABLED true
set_interface_property sampler EXPORT_OF ""
set_interface_property sampler PORT_NAME_MAP ""
set_interface_property sampler SVD_ADDRESS_GROUP ""
 

add_interface_port sampler PIO_INPUT export Input 32
add_interface_port sampler SAMPLE_CLK export Input 1
add_interface_port sampler PIO_INPUT_VALID export Input 1

# 
# connection point s_Global
# 
add_interface s_Global avalon end
set_interface_property s_Global addressUnits WORDS
set_interface_property s_Global associatedClock clock
set_interface_property s_Global associatedReset reset
set_interface_property s_Global bitsPerSymbol 8
set_interface_property s_Global burstOnBurstBoundariesOnly false
set_interface_property s_Global burstcountUnits WORDS
set_interface_property s_Global explicitAddressSpan 0
set_interface_property s_Global holdTime 0
set_interface_property s_Global linewrapBursts false
set_interface_property s_Global maximumPendingReadTransactions 0
set_interface_property s_Global readLatency 0
set_interface_property s_Global readWaitStates 0
set_interface_property s_Global readWaitTime 0
set_interface_property s_Global setupTime 0
set_interface_property s_Global timingUnits Cycles
set_interface_property s_Global writeWaitTime 0
set_interface_property s_Global ENABLED true
set_interface_property s_Global EXPORT_OF ""
set_interface_property s_Global PORT_NAME_MAP ""
set_interface_property s_Global SVD_ADDRESS_GROUP ""

add_interface_port s_Global avs_csr_address address Input 5
add_interface_port s_Global avs_csr_read read Input 1
add_interface_port s_Global avs_csr_write write Input 1
add_interface_port s_Global avs_csr_readdata readdata Output 32
add_interface_port s_Global avs_csr_writedata writedata Input 32
add_interface_port s_Global avs_csr_chipselect chipselect Input 1
set_interface_assignment s_Global embeddedsw.configuration.isFlash 0
set_interface_assignment s_Global embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s_Global embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s_Global embeddedsw.configuration.isPrintableDevice 0


# 
# connection point write_master
# 
add_interface write_master avalon start
set_interface_property write_master addressUnits SYMBOLS
set_interface_property write_master associatedClock clock
set_interface_property write_master associatedReset reset
set_interface_property write_master bitsPerSymbol 8
set_interface_property write_master burstOnBurstBoundariesOnly false
set_interface_property write_master burstcountUnits WORDS
set_interface_property write_master doStreamReads false
set_interface_property write_master doStreamWrites false
set_interface_property write_master holdTime 0
set_interface_property write_master linewrapBursts false
set_interface_property write_master maximumPendingReadTransactions 0
set_interface_property write_master readLatency 0
set_interface_property write_master readWaitTime 1
set_interface_property write_master setupTime 0
set_interface_property write_master timingUnits Cycles
set_interface_property write_master writeWaitTime 0
set_interface_property write_master ENABLED true
set_interface_property write_master EXPORT_OF ""
set_interface_property write_master PORT_NAME_MAP ""
set_interface_property write_master SVD_ADDRESS_GROUP ""

add_interface_port write_master avm_write_master_write write Output 1
add_interface_port write_master avm_write_master_address address Output 28
add_interface_port write_master avm_write_master_writedata writedata Output 32
add_interface_port write_master avm_write_master_waitrequest waitrequest Input 1






proc elaborate { } {

#**************************************************************************
 
    
#    # Internal parameters elaboration
    set rx_fifo_data_depth   [ get_parameter_value RX_DATA_FIFO_DEPTH ]
    set rx_fifo_data_widthu [ expr int (ceil (log($rx_fifo_data_depth) / log(2))) ]
    set_parameter_value RX_DATA_FIFO_WIDTHU $rx_fifo_data_widthu

    
}
